Switch to Py-Redis
breakfastny/flipdisc-python-framework pull request #5
Opened 2022-06-13 19:43 UTC by sebschlo

* fix some asyncio calls not being awaited

2022-06-13 19:43 UTC, sebschlo commented
Current dependencies on/for this PR:
* master
  * **PR #3** <a href="https://app.graphite.dev/github/pr/breakfastny/flipdisc-python-framework/3" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4** <a href="https://app.graphite.dev/github/pr/breakfastny/flipdisc-python-framework/4" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #5** <a href="https://app.graphite.dev/github/pr/breakfastny/flipdisc-python-framework/5" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
        * **PR #6** <a href="https://app.graphite.dev/github/pr/breakfastny/flipdisc-python-framework/6" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/breakfastny/flipdisc-python-framework/5?utm_source=stack-comment).

2022-06-13 21:36 UTC, sebschlo commented on flipdisc/framework/app.py
> +        retry = redis.retry.Retry(bo, 10)
@wrigby so this was my attempt to recreate the red.py file that I removed, by adding this retry functionality, but we might want to debate what the ideal retry behavior is

2022-06-14 17:54 UTC, mfazio26 commented on flipdisc/framework/app.py
> +        retry = redis.retry.Retry(bo, 10)
I don't have any insight into comparing methods, but I will say that the two most important bits are...

1. Connect, disconnect, and reconnect should get logged.
2. When re-connecting, `_on_redis_connect()` should run if/when applicable.

For context, one not-so-great behavior of the system is – lets say you have two instances of the Particles App – instances A and B. If instance A is running and you attempt to play instance B, it simply jams all of Instance B's config settings/values into the running instance A. The app is only ever killed when a different app/software is run. So, if redis goes down, it doesn't just effect the running app. Under the right conditions, playlists, scheduled triggered, etc can all fail and fall out of sync as a result because the app software can't do what it is supposed to.

2022-06-14 19:23 UTC, wrigby requested changes
See inline comments

2022-06-14 19:23 UTC, wrigby commented on flipdisc/framework/app.py
>  import redis
Just so our offline chat is recorded here, I think we're using the blocking API, but should be using the asyncio one:

```suggestion
import redis.asyncio as redis
```

2022-06-16 19:46 UTC, sebschlo commented on flipdisc/framework/app.py
> +        retry = redis.retry.Retry(bo, 10)
so the way this is working now is that whenever something connects/disconnects/etc to a channel, we'll receive a message of type "connect" or whatever it is, so the `_on_redis_message()` func will automatically log all of this activity

2022-06-16 20:21 UTC, sebschlo commented on flipdisc/framework/app.py
> +        retry = redis.retry.Retry(bo, 10)
![Screen Shot 2022-06-16 at 3.12.35 PM.png](https://graphite-user-uploaded-assets.s3.amazonaws.com/vuo0DHdLyDZiUNb8vsuM/5b5024d1-e7b0-43a3-8ad2-ac578cf1bb36/Screen%20Shot%202022-06-16%20at%203.12.35%20PM.png)

2022-06-17 13:31 UTC, mfazio26 commented on flipdisc/framework/app.py
> +        retry = redis.retry.Retry(bo, 10)
Got it. As long as it logs an issue with redis itself disconnecting/reconnecting – this looks great. For reference, this is what you get now if you kill redis-server while an app is running...
```
ERROR flipdisc.framework.red 38864 redis not connected, retrying in 1
```
...and then restart redis-server...
```
DEBUG flipdisc.framework.red 38864 redis connected
```

2022-06-21 14:18 UTC, sebschlo commented on flipdisc/framework/app.py
> +        retry = redis.retry.Retry(bo, 10)
Yeah, for actual Redis connection issues, think I'll have to add more logic, will do that today!

2022-06-22 13:15 UTC, wrigby commented on flipdisc/framework/app.py
>              self._task = None
This is a minor thing, but would it make more sense to make this class take a generic `args` parameter instead of `app`, then use `self.function(*self.args)` down below when calling it?

```suggestion
    class ScheduledFunction:
        def __init__(self, function, args, delay, periodic, loop):
            self.delay = delay
            self.function = function
            self.args = args
            self.periodic = periodic
            self.started = False
            self._loop = loop
            self._task = None
```

2022-06-22 13:42 UTC, sebschlo commented on flipdisc/framework/app.py
>              self._task = None
yeah for sure, might be nice to have the ability to pass other stuff

2022-06-24 15:00 UTC, closed without merging